services:
  otelcol:
    build:
      context: ..
      dockerfile: collector/Dockerfile
    command:
    - --config
    - /etc/otelcol/config.yaml
    # Add component/pipeline/etc ids to internal metrics.
    - --feature-gates=telemetry.newPipelineTelemetry
    environment:
    - OXIDE_HOST=${OXIDE_HOST}
    - OXIDE_TOKEN=${OXIDE_TOKEN}
    volumes:
    - ../collector/config.yaml:/etc/otelcol/config.yaml:ro
    - otelcol_data:/var/lib/otelcol
    ports:
    - "9091:9091"
    - "8888:8888"

  prometheus:
    image: prom/prometheus:latest
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - prometheus_data:/prometheus
    ports:
    - "9090:9090"
    depends_on:
    - otelcol

  loki:
    image: grafana/loki:3
    command: -config.file=/etc/loki/config.yaml
    ports:
    - "3100:3100"
    volumes:
    - ./loki.yaml:/etc/loki/config.yaml:ro
    - loki_data:/loki

  grafana:
    image: grafana/grafana:latest
    environment:
    - GF_AUTH_ANONYMOUS_ENABLED=true
    - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
    - "3000:3000"
    volumes:
    - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
    - ./grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml:ro
    - ./grafana/dashboards:/etc/grafana/dashboards:ro
    depends_on:
    - prometheus
    - loki

volumes:
  otelcol_data:
  prometheus_data:
  loki_data:
