{
 "title": "HTTP Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "oxide_host", "query": { "query": "label_values(oxide_host)" } },
   {
    "name": "id",
    "label": "Instance",
    "query": {
     "query": "label_values(http_service:request_latency_histogram_count{oxide_host=\"$oxide_host\"}, id)"
    }
   },
   {
    "name": "operation_id",
    "query": {
     "query": "label_values(http_service:request_latency_histogram_count{oxide_host=\"$oxide_host\"}, operation_id)"
    }
   },
   {
    "name": "status_code",
    "label": "Status Code",
    "query": {
     "query": "label_values(http_service:request_latency_histogram_count{oxide_host=\"$oxide_host\"}, status_code)"
    }
   }
  ]
 },
 "panels": [
  { "title": "nexus-external", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (operation_id) (rate(http_service:request_latency_histogram_count{oxide_host=\"$oxide_host\",id=~\"$id\",name=\"nexus-external\",operation_id=~\"$operation_id\",status_code=~\"$status_code\"}[$__rate_interval]))",
     "legendFormat": "{{operation_id}}"
    }
   ]
  },
  {
   "title": "5xx error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (operation_id) (rate(http_service:request_latency_histogram_count{oxide_host=\"$oxide_host\",id=~\"$id\",name=\"nexus-external\",operation_id=~\"$operation_id\",status_code=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "{{operation_id}}"
    }
   ]
  },
  {
   "title": "Latency p90 (non-5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le, operation_id) (rate(http_service:request_latency_histogram_bucket{oxide_host=\"$oxide_host\",id=~\"$id\",name=\"nexus-external\",operation_id=~\"$operation_id\",status_code=~\"$status_code\"}[$__rate_interval])))",
     "legendFormat": "{{operation_id}}"
    }
   ]
  },
  {
   "title": "Latency heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (le) (rate(http_service:request_latency_histogram_bucket{oxide_host=\"$oxide_host\",id=~\"$id\",name=\"nexus-external\",operation_id=~\"$operation_id\",status_code=~\"$status_code\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "nexus-internal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (operation_id) (rate(http_service:request_latency_histogram_count{oxide_host=\"$oxide_host\",id=~\"$id\",name=\"nexus-internal\",operation_id=~\"$operation_id\",status_code=~\"$status_code\"}[$__rate_interval]))",
     "legendFormat": "{{operation_id}}"
    }
   ]
  },
  {
   "title": "5xx error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (operation_id) (rate(http_service:request_latency_histogram_count{oxide_host=\"$oxide_host\",id=~\"$id\",name=\"nexus-internal\",operation_id=~\"$operation_id\",status_code=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "{{operation_id}}"
    }
   ]
  },
  {
   "title": "Latency p90 (non-5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le, operation_id) (rate(http_service:request_latency_histogram_bucket{oxide_host=\"$oxide_host\",id=~\"$id\",name=\"nexus-internal\",operation_id=~\"$operation_id\",status_code=~\"$status_code\"}[$__rate_interval])))",
     "legendFormat": "{{operation_id}}"
    }
   ]
  },
  {
   "title": "Latency heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by (le) (rate(http_service:request_latency_histogram_bucket{oxide_host=\"$oxide_host\",id=~\"$id\",name=\"nexus-internal\",operation_id=~\"$operation_id\",status_code=~\"$status_code\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "management-gateway-service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (operation_id) (rate(http_service:request_latency_histogram_count{oxide_host=\"$oxide_host\",id=~\"$id\",name=\"management-gateway-service\",operation_id=~\"$operation_id\",status_code=~\"$status_code\"}[$__rate_interval]))",
     "legendFormat": "{{operation_id}}"
    }
   ]
  },
  {
   "title": "5xx error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (operation_id) (rate(http_service:request_latency_histogram_count{oxide_host=\"$oxide_host\",id=~\"$id\",name=\"management-gateway-service\",operation_id=~\"$operation_id\",status_code=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "{{operation_id}}"
    }
   ]
  },
  {
   "title": "Latency p90 (non-5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le, operation_id) (rate(http_service:request_latency_histogram_bucket{oxide_host=\"$oxide_host\",id=~\"$id\",name=\"management-gateway-service\",operation_id=~\"$operation_id\",status_code=~\"$status_code\"}[$__rate_interval])))",
     "legendFormat": "{{operation_id}}"
    }
   ]
  },
  {
   "title": "Latency heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "sum by (le) (rate(http_service:request_latency_histogram_bucket{oxide_host=\"$oxide_host\",id=~\"$id\",name=\"management-gateway-service\",operation_id=~\"$operation_id\",status_code=~\"$status_code\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  { "title": "sled-agent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (operation_id) (rate(http_service:request_latency_histogram_count{oxide_host=\"$oxide_host\",id=~\"$id\",name=\"sled-agent\",operation_id=~\"$operation_id\",status_code=~\"$status_code\"}[$__rate_interval]))",
     "legendFormat": "{{operation_id}}"
    }
   ]
  },
  {
   "title": "5xx error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (operation_id) (rate(http_service:request_latency_histogram_count{oxide_host=\"$oxide_host\",id=~\"$id\",name=\"sled-agent\",operation_id=~\"$operation_id\",status_code=~\"5..\"}[$__rate_interval]))",
     "legendFormat": "{{operation_id}}"
    }
   ]
  },
  {
   "title": "Latency p90 (non-5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le, operation_id) (rate(http_service:request_latency_histogram_bucket{oxide_host=\"$oxide_host\",id=~\"$id\",name=\"sled-agent\",operation_id=~\"$operation_id\",status_code=~\"$status_code\"}[$__rate_interval])))",
     "legendFormat": "{{operation_id}}"
    }
   ]
  },
  {
   "title": "Latency heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "targets": [
    {
     "expr": "sum by (le) (rate(http_service:request_latency_histogram_bucket{oxide_host=\"$oxide_host\",id=~\"$id\",name=\"sled-agent\",operation_id=~\"$operation_id\",status_code=~\"$status_code\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}