{
 "title": "Resource utilization",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "oxide_host", "query": { "query": "label_values(oxide_host)" } },
   {
    "name": "silo_name",
    "query": {
     "query": "label_values(virtual_machine:check_total,silo_name)"
    }
   },
   {
    "name": "project_name",
    "query": {
     "query": "label_values(virtual_machine:check_total{oxide_host=\"$oxide_host\", silo_name=~\"$silo_name\"},project_name)"
    }
   },
   {
    "name": "instance_id",
    "query": {
     "query": "label_values(virtual_machine:check_total{oxide_host=\"$oxide_host\", silo_name=~\"$silo_name\", project_name=~\"$project_name\"},instance_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU % use by silo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (sum by (oxide_host, silo_name) (rate(virtual_machine:vcpu_usage_total{state=\"idle\", oxide_host=\"$oxide_host\", silo_name=~\"$silo_name\", project_name=~\"$project_name\", instance_id=~\"$instance_id\"}[5m])) / sum by (oxide_host, silo_name) (rate(virtual_machine:vcpu_usage_total{oxide_host=\"$oxide_host\", silo_name=~\"$silo_name\", project_name=~\"$project_name\", instance_id=~\"$instance_id\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top CPU % use by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - (sum by (oxide_host, silo_name, project_name, instance_id) (rate(virtual_machine:vcpu_usage_total{state=\"idle\", oxide_host=\"$oxide_host\", silo_name=~\"$silo_name\", project_name=~\"$project_name\", instance_id=~\"$instance_id\"}[5m])) / sum by (oxide_host, silo_name, project_name, instance_id) (rate(virtual_machine:vcpu_usage_total{oxide_host=\"$oxide_host\", silo_name=~\"$silo_name\", project_name=~\"$project_name\", instance_id=~\"$instance_id\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "Disk reads by silo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum by (oxide_host, silo_name) (rate(virtual_disk:reads_total{oxide_host=\"$oxide_host\", silo_name=~\"$silo_name\", project_name=~\"$project_name\", attached_instance_id=~\"$instance_id\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk reads by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum by (oxide_host, silo_name, attached_instance_id) (rate(virtual_disk:reads_total{oxide_host=\"$oxide_host\", silo_name=~\"$silo_name\", project_name=~\"$project_name\", attached_instance_id=~\"$instance_id\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk writes by silo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum by (oxide_host, silo_name) (rate(virtual_disk:writes_total{oxide_host=\"$oxide_host\", silo_name=~\"$silo_name\", project_name=~\"$project_name\", attached_instance_id=~\"$instance_id\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk writes by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum by (oxide_host, silo_name, attached_instance_id) (rate(virtual_disk:writes_total{oxide_host=\"$oxide_host\", silo_name=~\"$silo_name\", project_name=~\"$project_name\", attached_instance_id=~\"$instance_id\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk flushes by silo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (oxide_host, silo_name) (rate(virtual_disk:flushes_total{oxide_host=\"$oxide_host\", silo_name=~\"$silo_name\", project_name=~\"$project_name\", attached_instance_id=~\"$instance_id\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk flushes by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by (oxide_host, silo_name, attached_instance_id) (rate(virtual_disk:flushes_total{oxide_host=\"$oxide_host\", silo_name=~\"$silo_name\", project_name=~\"$project_name\", attached_instance_id=~\"$instance_id\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true
  },
  {
   "title": "Bytes sent by silo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (oxide_host, silo_name) (rate(instance_network_interface:bytes_sent_total{oxide_host=\"$oxide_host\", silo_name=~\"$silo_name\", project_name=~\"$project_name\", instance_id=~\"$instance_id\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes sent by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (oxide_host, silo_name, instance_id) (rate(instance_network_interface:bytes_sent_total{oxide_host=\"$oxide_host\", silo_name=~\"$silo_name\", project_name=~\"$project_name\", instance_id=~\"$instance_id\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes received by silo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (oxide_host, silo_name) (rate(instance_network_interface:bytes_received_total{oxide_host=\"$oxide_host\", silo_name=~\"$silo_name\", project_name=~\"$project_name\", instance_id=~\"$instance_id\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytes received by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (oxide_host, silo_name, instance_id) (rate(instance_network_interface:bytes_received_total{oxide_host=\"$oxide_host\", silo_name=~\"$silo_name\", project_name=~\"$project_name\", instance_id=~\"$instance_id\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets sent by silo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (oxide_host, silo_name) (rate(instance_network_interface:packets_sent_total{oxide_host=\"$oxide_host\", silo_name=~\"$silo_name\", project_name=~\"$project_name\", instance_id=~\"$instance_id\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets sent by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (oxide_host, silo_name, instance_id) (rate(instance_network_interface:packets_sent_total{oxide_host=\"$oxide_host\", silo_name=~\"$silo_name\", project_name=~\"$project_name\", instance_id=~\"$instance_id\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets received by silo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (oxide_host, silo_name) (rate(instance_network_interface:packets_received_total{oxide_host=\"$oxide_host\", silo_name=~\"$silo_name\", project_name=~\"$project_name\", instance_id=~\"$instance_id\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets received by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (oxide_host, silo_name, instance_id) (rate(instance_network_interface:packets_received_total{oxide_host=\"$oxide_host\", silo_name=~\"$silo_name\", project_name=~\"$project_name\", instance_id=~\"$instance_id\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets dropped by silo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (oxide_host, silo_name) (rate(instance_network_interface:packets_dropped_total{oxide_host=\"$oxide_host\", silo_name=~\"$silo_name\", project_name=~\"$project_name\", instance_id=~\"$instance_id\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Packets dropped by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by (oxide_host, silo_name, instance_id) (rate(instance_network_interface:packets_dropped_total{oxide_host=\"$oxide_host\", silo_name=~\"$silo_name\", project_name=~\"$project_name\", instance_id=~\"$instance_id\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}